// lex.yy.cpp generated by reflex 1.0.9 from /Users/trevorbergstrom/NewCompiler/quack.lxx

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_YYLTYPE             yy::location
#define REFLEX_OPTION_YYSTYPE             yy::parser::semantic_type
#define REFLEX_OPTION_bison_cc            true
#define REFLEX_OPTION_bison_cc_namespace  yy
#define REFLEX_OPTION_bison_cc_parser     parser
#define REFLEX_OPTION_bison_locations     true
#define REFLEX_OPTION_header_file         lex.yy.h
#define REFLEX_OPTION_lex                 yylex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           yy
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             lex.yy.cpp

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top{ user code %}                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "/Users/trevorbergstrom/NewCompiler/quack.lxx"

/* Quack scanner
 * Trevor Bergstrom
 * 10/5/2018
 * 2018 Fall version for RE/flex,
 * skeleton.
 *
 */

#include "quack.tab.hxx"  /* Generated by bison. */
#include "Messages.h"


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace yy {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  static const int comment = 1;
  static const int string = 2;
  virtual int yylex(yy::parser::semantic_type *yylval, yy::location *yylloc)
  {
    yylloc->step();
    int ret = yylex(*yylval);
    yylloc->end.line = matcher().lineno();
    yylloc->end.column = matcher().columno();
    return ret;
  }
  virtual int yylex(yy::parser::semantic_type& yylval);
};

} // namespace yy

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 14 "/Users/trevorbergstrom/NewCompiler/quack.lxx"

/* Externally visible file name --
* for error messages.
* FIXME: Need to extract this from structures that reflex passes
* or else find another way to dig it out.
*/
std::string yyfilename = "What file is this, anyway?";

/* Some strings can't be matched in one gulp.  We need
 * a buffer in which to assemble them from parts.
 */
std::string string_buf = "";
std::string mystring = "";

void yyerror (const std::string &msg, yy::position* where) {
     std::cout << where << ": " << msg;
}

/* Some long messages that don't fit well in the code below */

std::string BAD_ESC_MSG =
  "Illegal escape code; only \\\\, \\0, \\t, \\n, \\r, \\n are permitted";
std::string BAD_NL_STR =
  "Unclosed string?  Encountered newline in quoted string.";


#line 45 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
/* You'll probably want scanner states for both multi-line
   * comments and for triple-quote strings.  Do comments first,
   * because they're easier (you just throw away the text).  Then
   * do triple-quote strings.  You might consider doing the same for
   * normal strings with a single pair of double quotes, to avoid
   * writing a really ugly regex.  'comment' here is an example of
   * how to declare an exclusive scanner state.
   */

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON C++                                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int yy::Lexer::yylex(yy::parser::semantic_type& yylval)
{
  static const reflex::Pattern PATTERN_INITIAL("(?m)([=][=])|([<][=])|([>][=])|([\\x2d])|([\\x2b])|([\\x2a])|([/])|([\\x28])|([\\x29])|([;])|([\\x7b])|([\\x7d])|([=])|([\\x2e])|([:])|([>])|([<])|([,])|(class)|(def)|(if)|(elif)|(else)|(while)|(return)|(and)|(or)|(not)|(extends)|([0-9]*)|([A-Z_a-z][0-9A-Z_a-z]*)|([\\x09\\x0a\\x20]*)|([/][\\x2a])|([\"][\"][\"])|(\"(?:(?:[\\x5c][\"0\\x5cfnrt])|[^\\x0a\"\\x5c])*\")|(\"(?:(?:[\\x5c].)|[^\\x0a\\x5c])*\")|(\"(?:(?:[\\x5c].)|[^\"])*\\n)|(.)");
  static const reflex::Pattern PATTERN_comment("(?m)([^\\x2a]*)|([\\x2a][^/])|([\\x2a][/])");
  static const reflex::Pattern PATTERN_string("(?m)([\"][\"][\"])|(.)");
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  switch (start())
  {
    case INITIAL:
#line 63 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
/* We start with some tokens that are not value-bearing,
   * i.e., the parser needs to know only which token was matched.
   */

  /* Multi-character punctuation with names */
    break;
  }
  while (true)
  {
    switch (start())
    {
      case INITIAL:
        matcher().pattern(PATTERN_INITIAL);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 155 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return EOF; }

            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 63: [=][=]
#line 63 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return parser::token::EQUALS; }
            break;
          case 2: // rule at line 64: [<][=]
#line 64 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return parser::token::ATMOST; }
            break;
          case 3: // rule at line 65: [>][=]
#line 65 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::ATLEAST;}

   /* Single character punctuation.  Because a character
    * in C or C++ can be treated as an integer, Bison lets
    * us return a character as a token.
    * JFlex/Cup do not let you do this in Java.
    * Here are a few ... there are more.
    */
            break;
          case 4: // rule at line 73: [\x2d]
#line 73 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '-';}
            break;
          case 5: // rule at line 74: [\x2b]
#line 74 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '+';}
            break;
          case 6: // rule at line 75: [\x2a]
#line 75 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '*';}
            break;
          case 7: // rule at line 76: [/]
#line 76 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '/';}
            break;
          case 8: // rule at line 77: [\x28]
#line 77 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '(';}
            break;
          case 9: // rule at line 78: [\x29]
#line 78 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return ')';}
            break;
          case 10: // rule at line 79: [;]
#line 79 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return ';';}
            break;
          case 11: // rule at line 80: [\x7b]
#line 80 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '{';}
            break;
          case 12: // rule at line 81: [\x7d]
#line 81 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '}';}
            break;
          case 13: // rule at line 82: [=]
#line 82 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '=';}
            break;
          case 14: // rule at line 83: [\x2e]
#line 83 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '.';}
            break;
          case 15: // rule at line 84: [:]
#line 84 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return ':';}
            break;
          case 16: // rule at line 85: [>]
#line 85 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '>';}
            break;
          case 17: // rule at line 86: [<]
#line 86 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return '<';}
            break;
          case 18: // rule at line 87: [,]
#line 87 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return ',';}
  /* Keywords are essentially another kind of punctuation,
   * but since they also match the identifier pattern, we
   * need to be sure we give their patterns *before* the
   * identifier pattern.  Most scanner generators work this
   * way, but WARNING for Python PLY users:  PLY prioritizes
   * by length of the regular expression!
   * Here are a couple of examples.
   */

            break;
          case 19: // rule at line 97: class
#line 97 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return parser::token::CLASS; }
            break;
          case 20: // rule at line 98: def
#line 98 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return parser::token::DEF; }
            break;
          case 21: // rule at line 99: if
#line 99 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::IF;}
            break;
          case 22: // rule at line 100: elif
#line 100 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::ELIF;}
            break;
          case 23: // rule at line 101: else
#line 101 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::ELSE;}
            break;
          case 24: // rule at line 102: while
#line 102 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::WHILE;}
            break;
          case 25: // rule at line 103: return
#line 103 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::RETURN;}
            break;
          case 26: // rule at line 104: and
#line 104 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::AND;}
            break;
          case 27: // rule at line 105: or
#line 105 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::OR;}
            break;
          case 28: // rule at line 106: not
#line 106 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::NOT;}
            break;
          case 29: // rule at line 107: extends
#line 107 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::EXTENDS;}


   /* The following tokens are value-bearing:
    * We pass a value back to the parser by copying
    * it into the yylval parameter.  The parser
    * expects string values for identifiers and
    * string literals in yylval.str.  It expects integer
    * values for integer literals in yylval.num.
    * I'll give pattern for integer literals.
    * You'll need another for identifiers.  Remember to
    * 'strdup' the value returned by 'text()', or else it will
    * be clobbered by subsequent calls.
    */

            break;
          case 30: // rule at line 122: [0-9]*
#line 122 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ yylval.num = atoi(text()); return parser::token::INT_LIT; }

  /* You *can* write a one-line regular expression for matching a quoted string,
   * but you probably can't read it.  (I can't read mine.)  Scanner states and
   * simpler patterns are probably a better idea.
   * You almost certainly scanner states for triple quotes.
   * The tricky bit is catching errors, such as disallowed escape sequences
   * and unclosed quotes.
   */

            break;
          case 31: // rule at line 132: [A-Z_a-z][0-9A-Z_a-z]*
#line 132 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{return parser::token::IDENT;}
  /* Ignore whitespace */
            break;
          case 32: // rule at line 134: [\x09\x0a\x20]*
#line 134 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ ; }

   /* Multi-line comments */
            break;
          case 33: // rule at line 137: [/][\x2a]
#line 137 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ start(comment); }
            break;
          case 34: // rule at line 143: ["]["]["]
#line 143 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{start(string);}
            break;
          case 35: // rule at line 146: "(?:(?:[\x5c]["0\x5cfnrt])|[^\x0a"\x5c])*"
#line 146 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return parser::token::STR_LIT; }
            break;
          case 36: // rule at line 147: "(?:(?:[\x5c].)|[^\x0a\x5c])*"
#line 147 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{report::error(BAD_ESC_MSG);;}
            break;
          case 37: // rule at line 148: "(?:(?:[\x5c].)|[^"])*\n
#line 148 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{report::error(BAD_NL_STR);}

            break;
          case 38: // rule at line 150: .
#line 150 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{   report::error("Unexpected character '" + std::string(text()) + "'" +
       " at line " + std::to_string(lineno()) +
       ", column " + std::to_string(columno()));
   }

            break;
        }
        break;
      case comment:
        matcher().pattern(PATTERN_comment);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 138 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{report::error("END OF FILE ENCOUNTERED IN COMMENT");start(INITIAL);}
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 139: [^\x2a]*
#line 139 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ ; }
            break;
          case 2: // rule at line 140: [\x2a][^/]
#line 140 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ ; }
            break;
          case 3: // rule at line 141: [\x2a][/]
#line 141 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ start(INITIAL); }

            break;
        }
        break;
      case string:
        matcher().pattern(PATTERN_string);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
#line 155 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{ return EOF; }

            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 144: ["]["]["]
#line 144 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{start(INITIAL); return parser::token::STR_LIT;}
            break;
          case 2: // rule at line 145: .
#line 145 "/Users/trevorbergstrom/NewCompiler/quack.lxx"
{mystring += text();}
            break;
        }
        break;
      default:
        return 0;
    }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 158 "/Users/trevorbergstrom/NewCompiler/quack.lxx"

/* No main program here */

