# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/trevorbergstrom/NewCompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/trevorbergstrom/NewCompiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/trevorbergstrom/NewCompiler/CMakeFiles /Users/trevorbergstrom/NewCompiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/trevorbergstrom/NewCompiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lexer

# Build rule for target.
lexer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lexer
.PHONY : lexer

# fast build rule for target.
lexer/fast:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/build
.PHONY : lexer/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

ASTNode.o: ASTNode.cpp.o

.PHONY : ASTNode.o

# target to build an object file
ASTNode.cpp.o:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/ASTNode.cpp.o
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/ASTNode.cpp.o
.PHONY : ASTNode.cpp.o

ASTNode.i: ASTNode.cpp.i

.PHONY : ASTNode.i

# target to preprocess a source file
ASTNode.cpp.i:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/ASTNode.cpp.i
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/ASTNode.cpp.i
.PHONY : ASTNode.cpp.i

ASTNode.s: ASTNode.cpp.s

.PHONY : ASTNode.s

# target to generate assembly for a file
ASTNode.cpp.s:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/ASTNode.cpp.s
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/ASTNode.cpp.s
.PHONY : ASTNode.cpp.s

Messages.o: Messages.cpp.o

.PHONY : Messages.o

# target to build an object file
Messages.cpp.o:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/Messages.cpp.o
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/Messages.cpp.o
.PHONY : Messages.cpp.o

Messages.i: Messages.cpp.i

.PHONY : Messages.i

# target to preprocess a source file
Messages.cpp.i:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/Messages.cpp.i
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/Messages.cpp.i
.PHONY : Messages.cpp.i

Messages.s: Messages.cpp.s

.PHONY : Messages.s

# target to generate assembly for a file
Messages.cpp.s:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/Messages.cpp.s
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/Messages.cpp.s
.PHONY : Messages.cpp.s

lex.yy.o: lex.yy.cpp.o

.PHONY : lex.yy.o

# target to build an object file
lex.yy.cpp.o:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/lex.yy.cpp.o
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lex.yy.cpp.o
.PHONY : lex.yy.cpp.o

lex.yy.i: lex.yy.cpp.i

.PHONY : lex.yy.i

# target to preprocess a source file
lex.yy.cpp.i:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/lex.yy.cpp.i
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lex.yy.cpp.i
.PHONY : lex.yy.cpp.i

lex.yy.s: lex.yy.cpp.s

.PHONY : lex.yy.s

# target to generate assembly for a file
lex.yy.cpp.s:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/lex.yy.cpp.s
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/lex.yy.cpp.s
.PHONY : lex.yy.cpp.s

lex_driver.o: lex_driver.cpp.o

.PHONY : lex_driver.o

# target to build an object file
lex_driver.cpp.o:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/lex_driver.cpp.o
.PHONY : lex_driver.cpp.o

lex_driver.i: lex_driver.cpp.i

.PHONY : lex_driver.i

# target to preprocess a source file
lex_driver.cpp.i:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/lex_driver.cpp.i
.PHONY : lex_driver.cpp.i

lex_driver.s: lex_driver.cpp.s

.PHONY : lex_driver.s

# target to generate assembly for a file
lex_driver.cpp.s:
	$(MAKE) -f CMakeFiles/lexer.dir/build.make CMakeFiles/lexer.dir/lex_driver.cpp.s
.PHONY : lex_driver.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.cpp.s
.PHONY : parser.cpp.s

quack.tab.o: quack.tab.cxx.o

.PHONY : quack.tab.o

# target to build an object file
quack.tab.cxx.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/quack.tab.cxx.o
.PHONY : quack.tab.cxx.o

quack.tab.i: quack.tab.cxx.i

.PHONY : quack.tab.i

# target to preprocess a source file
quack.tab.cxx.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/quack.tab.cxx.i
.PHONY : quack.tab.cxx.i

quack.tab.s: quack.tab.cxx.s

.PHONY : quack.tab.s

# target to generate assembly for a file
quack.tab.cxx.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/quack.tab.cxx.s
.PHONY : quack.tab.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lexer"
	@echo "... parser"
	@echo "... ASTNode.o"
	@echo "... ASTNode.i"
	@echo "... ASTNode.s"
	@echo "... Messages.o"
	@echo "... Messages.i"
	@echo "... Messages.s"
	@echo "... lex.yy.o"
	@echo "... lex.yy.i"
	@echo "... lex.yy.s"
	@echo "... lex_driver.o"
	@echo "... lex_driver.i"
	@echo "... lex_driver.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... quack.tab.o"
	@echo "... quack.tab.i"
	@echo "... quack.tab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

